import "server-only";
import type { CollectedData, ZipDemographicData } from "@/lib/market-intelligence/types";
import type { ZipOpportunityRanking } from "@/lib/export/types";
const VERSION = "FHF-OPPORTUNITY-V1.1";
const clamp = (n:number,min=0,max=100)=>Math.max(min,Math.min(max,Number.isFinite(n)?n:0));
const r2=(n:number)=>Math.round(n*100)/100;
function priority(s:number):ZipOpportunityRanking["priorityLevel"]{return s>=80?"PRIORITY":s>=65?"STRONG":s>=50?"WATCH":"LOW";}
function placement(data:CollectedData){const ps=data.vaPrograms.data?.programs??[];const fit=(p:string)=>{const x=ps.find(v=>v.programName.startsWith(p));return x?.fitRank==="Best Immediate"?85:x?.fitRank==="Possible"?65:50};const va=data.geo.cocId?72:data.geo.metro?62:50;return clamp(fit("SSVF")*.35+fit("HUD-VASH")*.30+va*.20+50*.15);}
function pressure(data:CollectedData){const pit=data.pit.data,pop=data.census.data?.totalPopulation;if(pit?.totalHomeless!=null&&pop&&pop>0){const x=pit.totalHomeless/pop*10000;return x>=60?95:x>=40?85:x>=25?72:x>=15?58:x>=8?45:32}return 50;}
function need(data:CollectedData,z:ZipDemographicData){const vp=z.veteranPct??0,vc=vp>=10?90:vp>=8?80:vp>=6?70:vp>=4?58:vp>0?42:50;const p=z.povertyRatePct??0,v=p>=25?88:p>=18?74:p>=12?60:p>=8?46:p>0?32:50;let hs=50;const c=data.chas.data;if(c?.totalOccupied&&c.renterCostBurdened30pct!=null){const x=c.renterCostBurdened30pct/c.totalOccupied;hs=x>=.40?90:x>=.30?75:x>=.20?58:42}return clamp(pressure(data)*.40+vc*.30+v*.20+hs*.10);}
function economics(data:CollectedData,median:number|null){const f=data.fmr.data;if(!f||!median||median<=0)return 50;const x=f.fourBr/median;return x>=1.20?95:x>=1.10?85:x>=1?72:x>=.90?58:x>=.80?42:25;}
function properties(ls:NonNullable<CollectedData["rentcast"]["data"]>["sampleListings"],fmr4:number|null){if(!ls.length)return 35;const rs=ls.map(l=>l.rent).filter((v):v is number=>typeof v==="number").sort((a,b)=>a-b),m=rs.length?rs[Math.floor(rs.length/2)]:null;const d=ls.length>=10?90:ls.length>=6?78:ls.length>=3?65:52;const a=fmr4&&m?(m<=fmr4*.85?90:m<=fmr4?75:m<=fmr4*1.10?55:30):50;const q=ls.filter(l=>(l.bedrooms??0)>=3).length/ls.length,rooms=q>=.8?90:q>=.5?72:q>0?55:30;return clamp(d*.40+a*.35+rooms*.25);}
export function scoreZipOpportunities(data:CollectedData):ZipOpportunityRanking[]{const zd=data.zipDemographics;const demographics=zd?.data??[],listings=data.rentcast.data?.sampleListings??[];const byZip=new Map<string,typeof listings>();for(const l of listings){if(!l.zipCode)continue;const a=byZip.get(l.zipCode)??[];a.push(l);byZip.set(l.zipCode,a)}const candidates=demographics.filter(z=>byZip.has(z.zipCode));if(!candidates.length)return[];const pi=placement(data),f4=data.fmr.data?.fourBr??null;const rows=candidates.map((z):ZipOpportunityRanking=>{const ls=byZip.get(z.zipCode)??[],rs=ls.map(l=>l.rent).filter((v):v is number=>typeof v==="number").sort((a,b)=>a-b),median=rs.length?rs[Math.floor(rs.length/2)]:null;const vn=need(data,z),he=economics(data,median),pa=properties(ls,f4),vns=vn*.40,pis=pi*.20,hes=he*.25,pas=pa*.15,total=Math.round(clamp(vns+pis+hes+pas)),level=priority(total),estimated=data.pit.source.isDerived||data.chas.status!=="ok"||data.fmr.status!=="ok",confidence:ZipOpportunityRanking["confidenceLevel"]=zd?.status==="ok"&&data.pit.status==="ok"&&data.rentcast.status==="ok"?(estimated?"MEDIUM":"HIGH"):"ESTIMATED";return{zipCode:z.zipCode,rank:0,label:z.zipCode,veteranNeedIndex:r2(vn),veteranNeedScore:r2(vns),placementInfraIndex:r2(pi),placementInfraScore:r2(pis),housingEconomicsIndex:r2(he),housingEconomicsScore:r2(hes),propertyAvailIndex:r2(pa),propertyAvailScore:r2(pas),opportunityScore:total,priorityLevel:level,confidenceLevel:confidence,isEstimated:estimated,sourceGeography:`${z.zipCode} ZCTA + ${data.geo.cocId??data.geo.city} regional homelessness context`,sourceGeographyType:"zip",recommendation:level==="PRIORITY"?"Priority ZIP for property search.":level==="STRONG"?"Strong ZIP; begin targeted property search and verify local payment standard.":level==="WATCH"?"Watch ZIP; verify economics and referral capacity before committing.":"Lower priority with current evidence.",calculationVersion:VERSION}});return rows.sort((a,b)=>b.opportunityScore-a.opportunityScore||a.zipCode.localeCompare(b.zipCode)).map((r,i)=>({...r,rank:i+1}));}
